api: Api.agents
provider_type: inline::lightspeed_inline_agent
config_class: lightspeed_stack_providers.providers.inline.agents.lightspeed_inline_agent.config.LightspeedAgentsImplConfig
module: lightspeed_stack_providers.providers.inline.agents.lightspeed_inline_agent
adapter:
  adapter_type: lightspeed_inline_agent
  pip_packages: []
  config_class: lightspeed_stack_providers.providers.inline.agents.lightspeed_inline_agent.config.LightspeedAgentsImplConfig
  module: lightspeed_stack_providers.providers.inline.agents.lightspeed_inline_agent
api_dependencies: [ inference, safety, vector_io, vector_dbs, tool_runtime, tool_groups ]
optional_api_dependencies: []
